results_dir: "results"
sample_to_fastq:
    "test1": "data/test/test1.fastq.gz"
    "test2": "data/test/test2.fastq.gz"

reference_fasta: "/mnt/ssd/ref/nfcore/GLORI/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa"
reference_gtf: "/mnt/ssd/ref/nfcore/GLORI/Homo_sapiens.GRCh38.112.gtf"
