restart-times: 3
jobname: "{rule}.{wildcards}"
output-wait-time: 60
latency-wait: 60
use-conda: true
default-resources:
  - partition: cpu
  - mem_mb: 16000
  - threads: 1
jobs: 100
cluster:
  mkdir -p logs/slurm &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output=logs/slurm/{rule}-{wildcards}-%j.out
    --error=logs/slurm/{rule}-{wildcards}-%j.err
    --parsable
